# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20241103-212038-laminated-komodo

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
- name: WhitespaceTokenizer
  # Tokenizes the input based on whitespace. Works well with English text.
- name: RegexFeaturizer
  # Uses regex patterns for extracting features, helpful for identifying specific patterns.
- name: LexicalSyntacticFeaturizer
  # Extracts syntactic and lexical features from the text, enhancing entity recognition.
- name: CountVectorsFeaturizer
  # Converts words into vectors based on frequency, aiding intent classification.
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
  # This character-level featurizer is especially useful for short phrases or when handling spelling variations.
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  # The main classifier for intent and entity recognition. Adjust `epochs` based on training performance.
- name: EntitySynonymMapper
  # Maps entities to synonyms (e.g., 'laptop' = 'notebook').
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
  # Helps select responses for FAQ-like questions. Adjust `epochs` based on training performance.
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
'''Fallback policy for handling unconfident predictions'''
- name: RulePolicy
    core_fallback_action_name: "action_default_fallback"
    core_fallback_threshold: 0.3
